# Site settings {{ site._____ }}
title: Eric Moe
email:  geomoetric@gmail.com
name: "Eric Moe"
description: The design portfolio of Eric Moe.
baseurl:  # the subpath of your site, e.g. /blog/
prof_pic:   /img/prof_pic.jpg

# Your site's domain goes here (eg: https://yourusername.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:  #https://www.ericmoe.co #the base hostname & protocol for your site

  
# Social networking links used in footer. Update and remove as you like.
twitter:    https://twitter.com/geomoetric   
facebook:   https://www.facebook.com/geomoetric   
github: https://github.com/geomoetric  
stackexchange:  
linkedin:   https://www.linkedin.com/in/geomoetric
instagram:  https://www.instagram.com/geomoetric/
flickr:         
tumblr: http://geomoetric.tumblr.com/
dribbble:   https://dribbble.com/geomoetric/
pinterest:  https://www.pinterest.com/geomoetric/
reddit: https://www.reddit.com/user/geomoetric/
etsy:   https://www.etsy.com/shop/Geomoetric/
behance:    https://www.behance.net/EricMoe
# google plus id, include the '+', eg +mmistakes
google_plus:
  
# Social networking links used in share buttons. Update and remove as you like. 
username:
  twitter:      "geomoetric"
  github:     "geomoetric" 
  instagram:      "geomoetric"
  
# Jekyll SEO tag
author: geomoetric
twitter:
  username: geomoetric
facebook:
  app_id: 
  publisher: 
  admins:
logo: /favicon.ico/
social:
  name: Eric Moe
  links:
    - https://twitter.com/geomoetric
    - https://www.facebook.com/geomoetric
    - https://www.linkedin.com/in/geomoetric
    - https://github.com/geomoetric
    - https://www.instagram.com/geomoetric/
    - http://geomoetric.tumblr.com/
    - https://dribbble.com/geomoetric/
    - https://www.pinterest.com/geomoetric/
    - https://www.reddit.com/user/geomoetric/
    - https://www.etsy.com/shop/Geomoetric/
    - https://www.behance.net/EricMoe
google_verify:


  

#   http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:   America/Chicago
future: false  # publish future dated posts --  true, false (default) 


# Analytics stuff goes here
google_analytics:   UA-86525313-1  
  


# Build settings
markdown: kramdown

highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      image: /img/prof_pic.jpg


# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


# sass
sass:
  style: compressed
